# Generated by Django 5.1.7 on 2025-04-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_store_latitude_store_longitude_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='contact_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='store',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
